apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  labels:
    app: audit-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
      - name: audit-service
        image: hospital-management-system/audit-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3009
        envFrom:
        - configMapRef:
            name: hms-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: AUDIT_DB_URL
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  selector:
    app: audit-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3009
